/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mayinews_mv_JNI */

#ifndef _Included_com_mayinews_mv_JNI
#define _Included_com_mayinews_mv_JNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mayinews_mv_JNI
 * Method:    getString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_mayinews_mv_JNI_getString
  (JNIEnv * env, jobject obj);

#ifdef __cplusplus
}
#endif
#endif
